### ISSUE TITLE
I love your watch face

### ISSUE THREAD

**Issue by timothyhong-data** [Laverlin/Yet-Another-WatchFace#3]
I really love your watch face, but can I have another field to add city time? I need two:(

**Comment by Laverlin** [comment]
It would be possible to put the second city name on the bottom line, instead of moon phases, alarm icon and messages, but where to get data for it and how it will be different from the first one?
The data for the first city name is the current geo-position, but what would be the data for the second city?

**Comment by Mercerudy** [comment]
Agree, I'm loving the simplicity and data richness of this watch face.

As for the second alt location option, I could use this as well when traveling for work. It could just be manually set, like the Second Time zone option.

I think it would work best if it could squeeze in between the Second TZ and the exchange rate, so the user can their TZs altogether. The option to just turn it on or off, but save that alt location in settings would be nice.

**Comment by flocsy** [comment]
The place on the watch face is not a problem IMHO, but I can't understand the use-case. When you travel then I guess you want to see the local time, and set the Second Time to your home's timezone, so you know what's the time at home. Why do you need to also display your home town's name?
