### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by AndySardina** [Laverlin/Yet-Another-WatchFace#6]
Hi @Laverlin 

 Thank you very much for making this project Open Source. I have recently gotten a Garmin Watch and I am curious about what can be develop for it. I am trying to compile this project using Eclipse and the SDK v3.1.9 (I also tried v3.2.3) and I always get this error:

```
BUILD: ERROR: fr945: Z:\ConnectIQ\Yet-Another-WatchFace\source\YetAnotherWatchFaceView.mc:46: Undefined symbol "WatchServerTokenValue" detected.
BUILD: ERROR: fr945: Z:\ConnectIQ\Yet-Another-WatchFace\source\YetAnotherWatchFaceView.mc:47: Undefined symbol "ExchangeApiKeyValue" detected.
BUILD: ERROR: fr945: Z:\ConnectIQ\Yet-Another-WatchFace\source\YetAnotherWatchFaceView.mc:48: Undefined symbol "IsTest" detected.
```
This happens in the current `master` branch and also in the tag `Release-0.9.192`. I have perform a search in the project folder and I cannot find those values defined.

Could you please explain what I am doing wrong?

**Comment by Laverlin** [comment]
Hi Andy,
In order to compile, you need to add the file "secret.xml" in the settings folder.
The file should have the following content:
<strings><string id="LocationApiKeyValue">location key from bing location service</string><string id="IsTest">(1|0) depends on mode</string><string id="ExchangeApiKeyValue">currency exchange api key</string><string id="WatchServerTokenValue">API key from the watch server</string></strings>

**Comment by AndySardina** [comment]
Thank you very much!! This fixed the error!!
